import type { Rule, Rules } from '@fortress-validator/types';
import accepted from './accepted';
import alpha from './alpha';
import alphaDash from './alphaDash';
import alphaDashDot from './alphaDashDot';
import alphaNum from './alphaNum';
import array from './array';
import ascii from './ascii';
import between from './between';
import betweenLength from './betweenLength';
import boolean from './boolean';
import containsAll from './containsAll';
import containsAny from './containsAny';
import declined from './declined';
import different from './different';
import distinct from './distinct';
import domain from './domain';
import email from './email';
import endsWith from './endsWith';
import equals from './equals';
import file from './file';
import fileBetweenSize from './fileBetweenSize';
import fileMaxSize from './fileMaxSize';
import fileMinSize from './fileMinSize';
import fileSize from './fileSize';
import http from './http';
import httpOrHttps from './httpOrHttps';
import https from './https';
import integer from './integer';
import ip from './ip';
import ipv4 from './ipv4';
import ipv6 from './ipv6';
import json from './json';
import length from './length';
import lowercase from './lowercase';
import max from './max';
import maxLength from './maxLength';
import min from './min';
import minLength from './minLength';
import notContainsAll from './notContainsAll';
import notContainsAny from './notContainsAny';
import notEquals from './notEquals';
import notOneOf from './notOneOf';
import number from './number';
import numeric from './numeric';
import oneOf from './oneOf';
import protocol from './protocol';
import regex from './regex';
import required from './required';
import same from './same';
import size from './size';
import startsWith from './startsWith';
import string from './string';
import stringBetweenLength from './stringBetweenLength';
import stringLength from './stringLength';
import stringMaxLength from './stringMaxLength';
import stringMinLength from './stringMinLength';
import stringNotContainsAll from './stringNotContainsAll';
import stringNotContainsAny from './stringNotContainsAny';
import unique from './unique';
import uppercase from './uppercase';
import url from './url';

const rules: Rules = {
  accepted: accepted as Rule<unknown>,
  alpha: alpha as Rule<unknown>,
  alphaDash: alphaDash as Rule<unknown>,
  alphaDashDot: alphaDashDot as Rule<unknown>,
  alphaNum: alphaNum as Rule<unknown>,
  array: array as Rule<unknown>,
  ascii: ascii as Rule<unknown>,
  between: between as Rule<unknown>,
  betweenLength: betweenLength as Rule<unknown>,
  boolean: boolean as Rule<unknown>,
  containsAll: containsAll as Rule<unknown>,
  containsAny: containsAny as Rule<unknown>,
  declined: declined as Rule<unknown>,
  different: different as Rule<unknown>,
  distinct: distinct as Rule<unknown>,
  domain: domain as Rule<unknown>,
  email: email as Rule<unknown>,
  endsWith: endsWith as Rule<unknown>,
  equals: equals as Rule<unknown>,
  file: file as Rule<unknown>,
  fileBetweenSize: fileBetweenSize as Rule<unknown>,
  fileMaxSize: fileMaxSize as Rule<unknown>,
  fileMinSize: fileMinSize as Rule<unknown>,
  fileSize: fileSize as Rule<unknown>,
  http: http as Rule<unknown>,
  httpOrHttps: httpOrHttps as Rule<unknown>,
  https: https as Rule<unknown>,
  integer: integer as Rule<unknown>,
  ip: ip as Rule<unknown>,
  ipv4: ipv4 as Rule<unknown>,
  ipv6: ipv6 as Rule<unknown>,
  json: json as Rule<unknown>,
  length: length as Rule<unknown>,
  lowercase: lowercase as Rule<unknown>,
  max: max as Rule<unknown>,
  maxLength: maxLength as Rule<unknown>,
  min: min as Rule<unknown>,
  minLength: minLength as Rule<unknown>,
  notContainsAll: notContainsAll as Rule<unknown>,
  notContainsAny: notContainsAny as Rule<unknown>,
  notEquals: notEquals as Rule<unknown>,
  notOneOf: notOneOf as Rule<unknown>,
  number: number as Rule<unknown>,
  numeric: numeric as Rule<unknown>,
  oneOf: oneOf as Rule<unknown>,
  protocol: protocol as Rule<unknown>,
  regex: regex as Rule<unknown>,
  required: required as Rule<unknown>,
  same: same as Rule<unknown>,
  size: size as Rule<unknown>,
  startsWith: startsWith as Rule<unknown>,
  string: string as Rule<unknown>,
  stringBetweenLength: stringBetweenLength as Rule<unknown>,
  stringContainsAll: containsAll as Rule<unknown>,
  stringContainsAny: containsAny as Rule<unknown>,
  stringLength: stringLength as Rule<unknown>,
  stringMaxLength: stringMaxLength as Rule<unknown>,
  stringMinLength: stringMinLength as Rule<unknown>,
  stringNotContainsAll: stringNotContainsAll as Rule<unknown>,
  stringNotContainsAny: stringNotContainsAny as Rule<unknown>,
  unique: unique as Rule<unknown>,
  uppercase: uppercase as Rule<unknown>,
  url: url as Rule<unknown>,
};

export default rules;
